devtools::install_github("quanteda/quanteda.corpora")
# the devtools package needs to be installed for this to work
devtools::install_github("kbenoit/quanteda.dictionaries") 

install.packages("readtext")

library("quanteda.dictionaries")
library("quanteda")

# Load the relevant dictionary (relevant for analysis)
liwcdict <- dictionary(file = "C:/Users/Nicky/Documents/Text Analytics/Group Assignment/TAGit/LIWC/LIWC2007_English100131.dic", format = "LIWC")

# Read File
# Facebooks posts could be generated by  FB Netvizz 
# https://apps.facebook.com/netvizz
# Load FB posts as .csv-file from .zip-file 
imdbPost <- read.csv("C:/Users/Nicky/Documents/Text Analytics/Group Assignment/TAGit/data/imdb_master.csv", sep=",")

# Define the relevant column(s)
imdb_test <-as.character(imdbPost$review) #one column with 2700 entries
# Define as corpus
imdb_corp <-corpus(imdb_test)
class(imdb_corp)

# LIWC Application
imdb_liwc<-dfm(imdb_corp, dictionary=liwcdict)
View(imdb_liwc)
write.csv(imdb_liwc,file = "C:/Users/Nicky/Documents/Text Analytics/Group Assignment/TAGit/R_scripts/temp.csv", sep = ',')